"""Adding done and last_update columns

Revision ID: 183cfaae4493
Revises: None
Create Date: 2012-10-25 08:11:03.811958

"""

# revision identifiers, used by Alembic.
revision = '183cfaae4493'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('done', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('last_update', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_update')
    op.drop_column('jobs', 'done')
    ### end Alembic commands ###
