"""Adding index for tiles.job_id

Revision ID: 4fbba110ab8b
Revises: 183cfaae4493
Create Date: 2012-10-25 22:12:38.516115

"""

# revision identifiers, used by Alembic.
revision = '4fbba110ab8b'
down_revision = '183cfaae4493'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tiles_job_id_ndx', 'tiles', ['job_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tiles_job_id_ndx')
    ### end Alembic commands ###
