"""Added licenses table

Revision ID: 55009f9d3296
Revises: 173a7003596f
Create Date: 2012-12-20 21:58:33.616095

"""

# revision identifiers, used by Alembic.
revision = '55009f9d3296'
down_revision = '173a7003596f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('license_id', sa.Integer(), nullable=True))

    op.create_table('users_licenses',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('license', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['license'], ['licenses.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.username'], ),
    sa.PrimaryKeyConstraint()
    )
    # cannot drop column with SQLite
    #op.drop_column('jobs', u'requires_nextview')
    ### end Alembic commands ###

